name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Vérification des fichiers
        run: |
          test -f index.html
          test -f app.js
          test -f style.css

      - name: Build OK
        run: echo "Build réussi"